### ISSUE TITLE
MemoryTok: end-to-end flow design

### ISSUE THREAD

**Issue by arsen-ti** [trilogy-group/memorization-app#29]
I don't know why we keep calling it Tik-Tok-like when what I had in mind is Memrise-like app for sharing mnemonics. Tik-Tok is for vertical videos and it has features like subscription(or follow, I don't know since I've never used it), personal recommendations, chatting and all that garbage we don't need. Memrise is much more useful as a reference. It has quizzes, track of user's memorized words, there is structure in memorization, it has gamification. But the problem is that it's more difficult to clone.

**Comment by gao-ti** [comment]
Close due to duplication with #22 

We had different designs in mind before, where tiktok and our previous design shared a focus on socializing the users.

However, as we had in zoom talk and in google chats before

Moving on as your chapter-based memrise-like idea is better.
Please be assured that your design is affirmed and keep everyone posted about the progress of the end-to-end demo as well
